/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author Tsiry
 */
public class RoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomPanel1
     */
    public RoomPanel() {
        initComponents();
    }
    
    public JLabel getLbRoom1() {
        return lbRoom1;
    }

    public JLabel getLbRoom2() {
        return lbRoom2;
    }

    public JLabel getLbRoom3() {
        return lbRoom3;
    }

    public JLabel getLbRoom4() {
        return lbRoom4;
    }

    public JLabel getLbRoom5() {
        return lbRoom5;
    }

    public JLabel getLbRoom6() {
        return lbRoom6;
    }

    public JLabel getLbRoom7() {
        return lbRoom7;
    }

    public JLabel getLbRoom8() {
        return lbRoom8;
    }
    
    public JList<String> getOnlineList_rp() {
        return onlineList_rp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        onlineList_rp = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbRoom1 = new javax.swing.JLabel();
        lbRoom2 = new javax.swing.JLabel();
        lbRoom3 = new javax.swing.JLabel();
        lbRoom5 = new javax.swing.JLabel();
        lbRoom7 = new javax.swing.JLabel();
        lbRoom6 = new javax.swing.JLabel();
        lbRoom8 = new javax.swing.JLabel();
        lbRoom4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 150, 243));

        jPanel1.setBackground(new java.awt.Color(35, 145, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(35, 145, 234)));

        jPanel2.setBackground(new java.awt.Color(35, 145, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(231, 223, 223)));
        jPanel2.setMaximumSize(new java.awt.Dimension(95, 17));

        jLabel2.setBackground(new java.awt.Color(35, 145, 234));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Personnel en ligne");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);

        onlineList_rp.setBackground(new java.awt.Color(35, 145, 234));
        onlineList_rp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        onlineList_rp.setForeground(new java.awt.Color(255, 255, 255));
        onlineList_rp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        onlineList_rp.setSelectionBackground(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(onlineList_rp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Bureau de l'entreprise");

        jPanel3.setBackground(new java.awt.Color(33, 150, 243));

        lbRoom1.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom1.setText("Administration");
        lbRoom1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom2.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom2.setText("Service technique");
        lbRoom2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom3.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom3.setText("Comptable");
        lbRoom3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom5.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom5.setText("Etat civil");
        lbRoom5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom7.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom7.setText("taxe et douane");
        lbRoom7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom6.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom6.setText("Maintenance ");
        lbRoom6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom8.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom8.setText("Impot");
        lbRoom8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lbRoom4.setForeground(new java.awt.Color(255, 255, 255));
        lbRoom4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRoom4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_52px.png"))); // NOI18N
        lbRoom4.setText("Buget et Finance");
        lbRoom4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbRoom4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbRoom4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRoom4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbRoom4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRoom5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRoom3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbRoom5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRoom7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRoom8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbRoom1;
    private javax.swing.JLabel lbRoom2;
    private javax.swing.JLabel lbRoom3;
    private javax.swing.JLabel lbRoom4;
    private javax.swing.JLabel lbRoom5;
    private javax.swing.JLabel lbRoom6;
    private javax.swing.JLabel lbRoom7;
    private javax.swing.JLabel lbRoom8;
    private javax.swing.JList<String> onlineList_rp;
    // End of variables declaration//GEN-END:variables
}
